server:
  port: 7000
  servlet:
    context-path: /e-auth

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/e_auth
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        enable_lazy_load_no_trans: true

jwt:
  certificate:
    store:
      file: classpath:/certificate/jwt.jks
      password: password
    key:
      alias: jwt
      password: password


#security:
#  oauth2:
#    authorization:
#      jwt:
#        key-store: classpath:/certificate/jwt.jks
#        key-store-password: password
#        key-alias: jwt
#        key-password: password