server:
  port: 7002
  servlet:
    context-path: /e-connect

security:
  oauth2:
    client:
      access-token-uri: http://localhost:7000/e-auth/oauth/token
      user-authorization-uri: http://localhost:7000/e-auth/oauth/authorize
      client-id: app
      client-secret: password
#      accessTokenUri: http://localhost:7000/e-auth/oauth/token
#      userAuthorizationUri: http://localhost:7000/e-auth/oauth/authorize
#      clientId: app
#      clientSecret: password
#      client
    resource:
      user-info-uri: http://localhost:7003/e-resrc/api/user
#      userInfoUri: http://localhost:7003/e-resrc/api/user